### ISSUE TITLE
cannot run cover from eclipse. 

### ISSUE THREAD

**Issue by lud9393** [erlide/erlide#234]
I can launch cover from the console after adding it to the launch config in the start > module section, but when I start an Erlang cover configuration, this is what occcurs: 

the gui reports: 'error occured during launch' ....
from erlide.log

08:07:35,013 F: (BackendManager.java:90) : create execution backend cover_internal
08:07:35,013 F: (BackendFactory.java:56) : Create backend cover_internal
08:07:35,014 F: (OtpNodeProxy.java:301) : Runtime cover_internal@blue-data-10062 starting
08:07:35,014 F: (OtpNodeProxy.java:419) : START node :> [./bin/erl, -sname, cover_internal@blue-data-10062] *** /Applications/eclipse/Eclipse.app/Contents/MacOS
08:07:35,021 S: (OtpNodeProxy.java:432) : Could not create runtime: [./bin/erl, -sname, cover_internal@blue-data-10062]
08:07:35,021 S: (OtpNodeProxy.java:433) : Cannot run program "./bin/erl" (in directory "."): error=2, No such file or directory
java.io.IOException: Cannot run program "./bin/erl" (in directory "."): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
	at org.erlide.runtime.OtpNodeProxy$OtpNodeProxyService.startRuntimeProcess(OtpNodeProxy.java:429)
	at org.erlide.runtime.OtpNodeProxy$OtpNodeProxyService.startUp(OtpNodeProxy.java:354)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:55)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
	... 5 more

the exception stack trace from eclipse:
java.lang.IllegalStateException: Expected the service to be RUNNING, but the service has FAILED
	at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:285)
	at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:229)
	at com.google.common.util.concurrent.AbstractExecutionThreadService.awaitRunning(AbstractExecutionThreadService.java:197)
	at org.erlide.runtime.RestartableService.awaitRunning(RestartableService.java:107)
	at org.erlide.runtime.OtpNodeProxy.ensureRunning(OtpNodeProxy.java:321)
	at org.erlide.backend.internal.BackendFactory.createBackend(BackendFactory.java:66)
	at org.erlide.backend.internal.BackendManager.createExecutionBackend(BackendManager.java:91)
	at org.erlide.backend.launch.ErlangLaunchDelegate.launch(ErlangLaunchDelegate.java:57)
	at org.erlide.cover.runtime.launch.CoverLaunchConfigurationDelegate.launch(CoverLaunchConfigurationDelegate.java:27)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:858)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:707)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1018)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: java.lang.Exception: no runtime
	at org.erlide.runtime.OtpNodeProxy$OtpNodeProxyService.startUp(OtpNodeProxy.java:356)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:55)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:744)

**Comment by vladdu** [comment]
The cover plugin is unfortunately not tested regularily, so I suppose that some change to the core left it in a bad state. I will check it out.

**Comment by lud9393** [comment]
Thanks! btw: my eclipse ver. is a bit old: 4.3.1, 4.5 is latest.

**Comment by vladdu** [comment]
That's ok, our target is 4.2, because enterprise users can't update fast.
