### ISSUE TITLE
can't handle erl runtime version with 4 segments (17.5.6.1)

### ISSUE THREAD

**Issue by freboy** [erlide/erlide#235]
I have problems to set new erl runtime in the preferences.
It works with older OTP releases but fails for OTP17.

I used eclipse 4.5.0 with Erlide v0.29.12.201507101554, but it failed with other versions also

**Comment by freboy** [comment]
This is how it looks:
![2015-08-25_erlide_add_runtime_exception_otp17](https://cloud.githubusercontent.com/assets/13961261/9466852/ffc78f8a-4b37-11e5-8d64-f6afc468fe56.png)

I know the way the version numbers are tracked changed in this release, so it might be related to that.

Error message:
java.lang.NullPointerException
	at org.erlide.runtime.runtimeinfo.RuntimeInfoCatalog.addRuntime(RuntimeInfoCatalog.java:64)
	at org.erlide.runtime.runtimeinfo.RuntimeInfoCatalog.setRuntimes(RuntimeInfoCatalog.java:51)
	at org.erlide.ui.prefs.RuntimePreferencePage.performOk(RuntimePreferencePage.java:791)
	at org.eclipse.jface.preference.PreferenceDialog$12.run(PreferenceDialog.java:925)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:909)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:409)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.okPressed(WorkbenchPreferenceDialog.java:168)
	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:233)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:63)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by vladdu** [comment]
It works with all versions up to 18. Is your v17 install built and working? The version string is retrieved from the OTP_VERSION file (from the root or any releases directory).

**Comment by freboy** [comment]
The OTP is installed and works.
I have a version file located under this path:
./lib/erlang/releases/17/OTP_VERSION

**Comment by vladdu** [comment]
How was Erlang 17 installed? From OS package manager, or from source? In the former case, there are OSs that install things a bit differently. It should always work when erlang is built from source.

We check for the version in $OTP/OTP_VERSION, $OTP/releases/*/OTP_VERSION and $OTP/bin/start.boot, where $OTP is of course the root directory of the erlang installation.

Without knowing exactly what happens in your case, the only thing I can do is to try to print a more informative error message.

**Comment by freboy** [comment]
I saw you had changed the erlide, but when I tried the nightly build, I still get the same error.
Maybe I should clarify how we use the OTP:
We have built it from source and stored it under a certain path. This path is added to the environment settings. The version file is located under $OTP/releases/*/OTP_VERSION in our case.

I also tried to put it in the root directory but got the same error. Does erlide look in the specified path (and sub directories) first which is entered in the preferences dialog?

**Comment by vladdu** [comment]
The relevant code is here: https://github.com/erlide/erlide/blob/pu/org.erlide.runtime/src/org/erlide/runtime/runtimeinfo/RuntimeInfo.java#L217-L231

I will add some more debug printouts later today, hopefully you can then see what is happening.

**Comment by vladdu** [comment]
Please try the latest nightly build. There will be printouts prefixed with "> ".

**Comment by freboy** [comment]
Sorry, I was interrupted by other things, so I did not have time to investigate this further.

I did not see any of that printouts you added.
I downloaded the erl-ide sources and wanted to debug it further by replacing the org.erlide.runtime.runtimeinfo with a local copy with more printouts. Is it possible to patch it like this?

**Comment by vladdu** [comment]
No problem.

If you can get everything to build and execute, of course it's much simpler if you can add printouts (or debug) yourself, it takes less time to get feedback. Note that you need to have Xtend installed in your main Eclipse. (update site: http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/)

In this case, the printouts are in org.erlide.runtime\src\org\erlide\runtime\runtimeinfo\RuntimeInfo.java. The changes I made are on the "pu" branch.

Please let me know if you need further help.

**Comment by freboy** [comment]
Could you please check if use the right nightly version?
I am using this one but do not see any printouts:
*** starting Erlide v0.29.13.201510161913 (core=0.24.13.201510161913) (model api=0.24.12.201510161913) *** (ISO-8859-1) ui

I have downloaded the erlide sources. How can I rebuild the org.erlide.runtime_....jar from that?

**Comment by vladdu** [comment]
Sorry, I had pushed changes that removed those printouts. Try the latest nightly build.

Regarding building from source, it is a bit tricky to set up, I'm not sure I can remember all details right now... If you only need to build the Java code, you need to install support for Xtend 2.8+ from the Eclipse marketplace. Then probably easiest is to create an update sire project, add the org.erlide feature to it and generate the update site. Since your installed erlide doesn't work, the new *.kernel.* plugins will contain no beam files, so make sure you don't use them. Copy over only the new org.erlide.runtime jar.

I hope that will work.

**Comment by freboy** [comment]
Now I got something!
The version extraction seems actually to work:
(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1

But in the Dialogue no Version number is displayed and I get the same NullPointer as before:
java.lang.NullPointerException
	at org.erlide.runtime.runtimeinfo.RuntimeInfoCatalog.addRuntime(RuntimeInfoCatalog.java:68)
	at org.erlide.runtime.runtimeinfo.RuntimeInfoCatalog.setRuntimes(RuntimeInfoCatalog.java:52)
I also do not see this printout:
    public RuntimeVersion getVersion() {
    	System.out.println("> current version is " + version);

**Comment by vladdu** [comment]
I pushed some more printouts, there will be a new nightly in 10-12 minutes. I have to go now, but can look at it tomorrow again.

**Comment by freboy** [comment]
(ErlangCore.java:79) : *** starting Erlide v0.29.13.201510202047 (core=0.24.13.201510202047) (model api=0.24.12.201510202047) *** (ISO-8859-1) ui
 
(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1
(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1
(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1

**Comment by freboy** [comment]
Could you add some printouts like this to RuntimeInfoCatalog?

    @Override
    public synchronized void addRuntime(final RuntimeInfo rt) {
        System.out.println("> addRT start with " + rt.toString());
        System.out.println("> addRT getVersion " + rt.getVersion());
        System.out.println("> addRT isCompatible " + rt.getVersion().isCompatible(OLDEST_SUPPORTED_VERSION));
        System.out.println("> addRT name " + rt.getName());
        if (rt.getVersion().isCompatible(OLDEST_SUPPORTED_VERSION)
                && !runtimes.containsKey(rt.getName())) {
            runtimes.put(rt.getName(), rt);
        }
    }

**Comment by vladdu** [comment]
Ok, please wait for it to build,  ~10 minutes, check that the latest nightly has today's date.

**Comment by freboy** [comment]
Thank you for the update! It looks like it finds the version but returns NULL anyway:

*** starting Erlide v0.29.13.201510221028 (core=0.24.13.201510221028) (model api=0.24.12.201510221028) *** (ISO-8859-1) ui

(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1
(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1
(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1
(RuntimeInfoCatalog.java:68) : > addRT start with Runtime<erlang (/myotp/r16b03-06/i686-pc-linux-gnu/lib/erlang) R16B03-1 []>
(RuntimeInfoCatalog.java:69) : > addRT getVersion R16B03-1
(RuntimeInfoCatalog.java:70) : > addRT isCompatible true
(RuntimeInfoCatalog.java:72) : > addRT name erlang
(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1
(RuntimeInfoCatalog.java:68) : > addRT start with Runtime<OTP17 (/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang) null []>
(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1
(RuntimeInfoCatalog.java:69) : > addRT getVersion null
(RuntimeInfo.java:218) : > get version for /myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang
(RuntimeInfo.java:223) : > root: null
(RuntimeInfo.java:255) : > check: '/myotp/17.5.6.1/x86_64-pc-linux-gnu/lib/erlang/releases/17'
(RuntimeInfo.java:228) : > releases: 17.5.6.1

**Comment by vladdu** [comment]
What's strange is that it tries with 17.5.6.1 over and over again...

Try this: in the runtimes dialog, remove all of them but one (the one that you will use) and see what happens when you restart. 

If it doesn't work, remove the runtime, add one of the others and see if that helps.

Then check the respective directories and try to see what is different between them...

**Comment by freboy** [comment]
I finally found the fault!

After trying around different versions I discovered that the problem is caused by the fact that this is a patch release which has 4 levels of version numbering, while erlide only supports 3: major.minor.micro.
When I remove the last field so my release is called 17.5.6 it works.

**Comment by vladdu** [comment]
Cool! Then I will remove the printouts and fix this issue (will rename the issue too).

**Comment by freboy** [comment]
Hi,
thank you for the quick fix!

I verified that it works with the latest version on nightly. How is the release plan? Will there be an official release soon containing this and other patches?

**Comment by vladdu** [comment]
I don't really have a release plan, but when there are some fixes, I make them official. I will try to publish the current version today or tomorrow.

**Comment by vladdu** [comment]
Version 0.30.0 is available now. Enjoy!
