### ISSUE TITLE
Custom kerl erlang can cause exception

### ISSUE THREAD

**Issue by lixen** [erlide/erlide#246]
After I installed Bashos patched kerl build erlide failed to start.

```
./kerl build git git://github.com/basho/otp.git OTP_R16B02_basho8 R16B02-basho8
./kerl install R16B02-basho8 ~/erlang/R16B02-basho8
```

```
Root exception:
java.lang.NumberFormatException: For input string: "02_basho8"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at org.erlide.runtime.runtimeinfo.RuntimeVersion$Serializer.parseOld(RuntimeVersion.java:88)
	at org.erlide.runtime.runtimeinfo.RuntimeVersion$Serializer.parse(RuntimeVersion.java:140)
	at org.erlide.runtime.runtimeinfo.RuntimeInfo.getVersion(RuntimeInfo.java:212)
	at org.erlide.runtime.runtimeinfo.RuntimeInfo.getVersion(RuntimeInfo.java:204)
	at org.erlide.runtime.runtimeinfo.RuntimeInfoCatalog.addRuntime(RuntimeInfoCatalog.java:68)
	at org.erlide.runtime.runtimeinfo.RuntimeInfoCatalog.initializeRuntimesList(RuntimeInfoCatalog.java:191)
	at org.erlide.runtime.runtimeinfo.RuntimeInfoCatalog.setRuntimes(RuntimeInfoCatalog.java:48)
	at org.erlide.runtime.api.RuntimeCore.getRuntimeInfoCatalog(RuntimeCore.java:21)
	at org.erlide.backend.BackendCore.getRuntimeInfoCatalog(BackendCore.java:27)
	at org.erlide.backend.internal.BackendActivator.start(BackendActivator.java:21)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
```

**Comment by vladdu** [comment]
ah, I only assumed that version numbers are numeric... I'll try to fix this today.

**Comment by vladdu** [comment]
note to self: version here is R16B02_basho8

**Comment by vladdu** [comment]
Fixed in nightly

**Comment by lixen** [comment]
Thanks!
